import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Socialmedia from "@/components/socialmedia"; // Adjust the path to where your FloatingSocialMedia component is located

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Socialmedia /> {/* Adding Floating Social Media icons */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
